//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.CoolApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssemblyUtilResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssemblyUtilResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustInTheWind.CoolApp.Properties.AssemblyUtilResources", typeof(AssemblyUtilResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving the description for assembly &quot;{0}&quot;..
        /// </summary>
        internal static string AssemblyUtil_AssemblyDescription_Error {
            get {
                return ResourceManager.GetString("AssemblyUtil_AssemblyDescription_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving the title for assembly &quot;{0}&quot;..
        /// </summary>
        internal static string AssemblyUtil_AssemblyTitle_Error {
            get {
                return ResourceManager.GetString("AssemblyUtil_AssemblyTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving the company name for assembly &quot;{0}&quot;..
        /// </summary>
        internal static string AssemblyUtil_CompanyName_Error {
            get {
                return ResourceManager.GetString("AssemblyUtil_CompanyName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving the copyright information for assembly &quot;{0}&quot;..
        /// </summary>
        internal static string AssemblyUtil_CopyrightInformation_Error {
            get {
                return ResourceManager.GetString("AssemblyUtil_CopyrightInformation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving the informational version for assembly &quot;{0}&quot;..
        /// </summary>
        internal static string AssemblyUtil_InformationalVersion_Error {
            get {
                return ResourceManager.GetString("AssemblyUtil_InformationalVersion_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving the product name for assembly &quot;{0}&quot;..
        /// </summary>
        internal static string AssemblyUtil_ProductName_Error {
            get {
                return ResourceManager.GetString("AssemblyUtil_ProductName_Error", resourceCulture);
            }
        }
    }
}
