//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.CoolApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VersionCheckerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VersionCheckerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustInTheWind.CoolApp.Properties.VersionCheckerResources", typeof(VersionCheckerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking url: {0}.
        /// </summary>
        internal static string VersionCheckerWindow_Checking {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory where to download the new version..
        /// </summary>
        internal static string VersionCheckerWindow_Download_SelectDestinationDirectory {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_Download_SelectDestinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download was canceled..
        /// </summary>
        internal static string VersionCheckerWindow_DownloadCanceled {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_DownloadCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading the new version.
        ///Error message: {0}.
        /// </summary>
        internal static string VersionCheckerWindow_DownloadError {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} {1}:    {2:#,# kB} / {3:#,# kB}.
        /// </summary>
        internal static string VersionCheckerWindow_Downloading {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS !!!
        ///The file was successfully downloaded to
        ///{0}
        ///
        ///Note! Please be sure Azzul is not running while the new version is installing..
        /// </summary>
        internal static string VersionCheckerWindow_DownloadSuccess {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_DownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS !!!
        ///The file was successfully downloaded. Enjoy! :).
        /// </summary>
        internal static string VersionCheckerWindow_DownloadSuccess_Short {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_DownloadSuccess_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another file is already downloading..
        /// </summary>
        internal static string VersionCheckerWindow_Error_AlreadyDownloading {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_Error_AlreadyDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no new version available..
        /// </summary>
        internal static string VersionCheckerWindow_NoNewVersion {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; already exists. Overwrite?.
        /// </summary>
        internal static string VersionCheckerWindow_OverwriteQuestion {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_OverwriteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        internal static string VersionCheckerWindow_OverwriteQuestion_Title {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_OverwriteQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for new version....
        /// </summary>
        internal static string VersionCheckerWindow_StatusText_Checking {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_StatusText_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading the new version..
        /// </summary>
        internal static string VersionCheckerWindow_StatusText_DownloadError {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_StatusText_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string VersionCheckerWindow_StatusText_Error {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_StatusText_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while checking for new version.
        /// </summary>
        internal static string VersionCheckerWindow_StatusText_ErrorChecking {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_StatusText_ErrorChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available: {0}.
        /// </summary>
        internal static string VersionCheckerWindow_StatusText_NewVersionAvailable {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_StatusText_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new version available.
        /// </summary>
        internal static string VersionCheckerWindow_StatusText_NoNewVersion {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_StatusText_NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version description:
        ///{0}.
        /// </summary>
        internal static string VersionCheckerWindow_VersionDescription {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_VersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version description:
        ///{0}
        ///
        ///For download please visit {1}.
        /// </summary>
        internal static string VersionCheckerWindow_VersionDescriptionNoDownload {
            get {
                return ResourceManager.GetString("VersionCheckerWindow_VersionDescriptionNoDownload", resourceCulture);
            }
        }
    }
}
