//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.Azzul.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GatesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GatesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustInTheWind.Azzul.Properties.GatesResources", typeof(GatesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gate &quot;{0}&quot; cannot be used because it is not added to the loaded Gates list..
        /// </summary>
        internal static string InternalError_LoadedGates_GateNotLoaded {
            get {
                return ResourceManager.GetString("InternalError_LoadedGates_GateNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another gate with the same name was already loaded. Name: &quot;{0}&quot;.
        /// </summary>
        internal static string InternalError_LoadedGates_ManagerContainsGateWithSameName {
            get {
                return ResourceManager.GetString("InternalError_LoadedGates_ManagerContainsGateWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the gate can not be empty string..
        /// </summary>
        internal static string InternalError_LoadedGates_NameIsEmptyString {
            get {
                return ResourceManager.GetString("InternalError_LoadedGates_NameIsEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the gate can not be null..
        /// </summary>
        internal static string InternalError_LoadedGates_NameIsNull {
            get {
                return ResourceManager.GetString("InternalError_LoadedGates_NameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list contains two gates with the same names. Name: &quot;{0}&quot;.
        /// </summary>
        internal static string InternalError_LoadedGates_TwoGatesWithSameName {
            get {
                return ResourceManager.GetString("InternalError_LoadedGates_TwoGatesWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LoadedGates service encountered an unknown error..
        /// </summary>
        internal static string InternalError_LoadedGates_UnknownError {
            get {
                return ResourceManager.GetString("InternalError_LoadedGates_UnknownError", resourceCulture);
            }
        }
    }
}
