//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.Versioning.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VersioningResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VersioningResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustInTheWind.Versioning.Properties.VersioningResources", typeof(VersioningResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document containing the version information could not be retrieved..
        /// </summary>
        internal static string Error_VersionDocumentCannotBeRetrieved {
            get {
                return ResourceManager.GetString("Error_VersionDocumentCannotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for the &quot;version&quot; attribute..
        /// </summary>
        internal static string Error_VersionInformation_InvalidVersionsFile_InvalidVersionAttribute {
            get {
                return ResourceManager.GetString("Error_VersionInformation_InvalidVersionsFile_InvalidVersionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not contain version information for application &quot;{0}&quot;..
        /// </summary>
        internal static string Error_VersionInformation_NoInformationAboutApplication {
            get {
                return ResourceManager.GetString("Error_VersionInformation_NoInformationAboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;version&quot; tag. Attribute &quot;version&quot; was not found..
        /// </summary>
        internal static string Error_VersionInformation_VersionAttributeNotFound {
            get {
                return ResourceManager.GetString("Error_VersionInformation_VersionAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum check time can be set only when no asynchronous check is performed..
        /// </summary>
        internal static string InternalError_MinCheckTimeCannotBeSet {
            get {
                return ResourceManager.GetString("InternalError_MinCheckTimeCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured when checking for a new version..
        /// </summary>
        internal static string InternalError_UnknownError {
            get {
                return ResourceManager.GetString("InternalError_UnknownError", resourceCulture);
            }
        }
    }
}
