//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.Versioning.WinForms.Mvp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustInTheWind.Versioning.WinForms.Mvp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another asynchronous operation is already started..
        /// </summary>
        internal static string Error_AnotherAsyncOperationIsRunning {
            get {
                return ResourceManager.GetString("Error_AnotherAsyncOperationIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both an Azzul item and a catalog are needed to set the current item..
        /// </summary>
        internal static string Error_BothItemAndCatalogNeeded {
            get {
                return ResourceManager.GetString("Error_BothItemAndCatalogNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the Azzul section of the configuration file.
        ///Reason: {0}.
        /// </summary>
        internal static string Error_ConfigurationManager_ErrorReadingAzzulSection {
            get {
                return ResourceManager.GetString("Error_ConfigurationManager_ErrorReadingAzzulSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drive &quot;{0}&quot; is not ready to be read..
        /// </summary>
        internal static string Error_DriveNotReadyForRead {
            get {
                return ResourceManager.GetString("Error_DriveNotReadyForRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the elements of type CatalogConfigurationElement can be passed as arguments..
        /// </summary>
        internal static string InternalError_Configuration_NotCatalogConfigurationElement {
            get {
                return ResourceManager.GetString("InternalError_Configuration_NotCatalogConfigurationElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error in the configuration mechanism..
        /// </summary>
        internal static string InternalError_ConfigurationManager_UnknownError {
            get {
                return ResourceManager.GetString("InternalError_ConfigurationManager_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not finish the asynchronous operation. The executed delegate could not be retrieved..
        /// </summary>
        internal static string InternalError_FinishAsyncOperation_InvalidDelegate {
            get {
                return ResourceManager.GetString("InternalError_FinishAsyncOperation_InvalidDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View was already set..
        /// </summary>
        internal static string InternalError_MvpViewWasAlreadySet {
            get {
                return ResourceManager.GetString("InternalError_MvpViewWasAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the catalogs in the enumeration is null..
        /// </summary>
        internal static string InternalError_OpenedCatalogsService_ListContainsNullCatalog {
            get {
                return ResourceManager.GetString("InternalError_OpenedCatalogsService_ListContainsNullCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown internal error..
        /// </summary>
        internal static string InternalError_UnknownError {
            get {
                return ResourceManager.GetString("InternalError_UnknownError", resourceCulture);
            }
        }
    }
}
